echo -e "\n\nBFS1\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search BFS -s 2 -i input1.txt -o out.txt;
echo -e "\n\nDFS1\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search DFS -s 2 -i input1.txt -o out.txt;
echo -e "\n\nAS1\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search AStar -s 2 -i input1.txt -o out.txt;
echo -e "\n\nB51\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 5 -s 2 -i input1.txt -o out.txt;
echo -e "\n\nB101\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 10 -s 2 -i input1.txt -o out.txt;
echo -e "\n\nB501\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 50 -s 2 -i input1.txt -o out.txt;
echo -e "\n\nBFS2\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search BFS -s 2 -i input2.txt -o out.txt;echo -e "\n\nBFS1\n" >> timelog;
echo -e "\n\nDFS2\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search DFS -s 2 -i input2.txt -o out.txt;
echo -e "\n\nAS2\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search AStar -s 2 -i input2.txt -o out.txt;
echo -e "\n\nB52\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 5 -s 2 -i input2.txt -o out.txt;
echo -e "\n\nB102\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 10 -s 2 -i input2.txt -o out.txt;
echo -e "\n\nB502\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 50 -s 2 -i input2.txt -o out.txt;
echo -e "\n\nBFS3\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search BFS -s 2 -i input3.txt -o out.txt;
echo -e "\n\nDFS3\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search DFS -s 2 -i input3.txt -o out.txt;
echo -e "\n\nAS3\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search AStar -s 2 -i input3.txt -o out.txt;
echo -e "\n\nB53\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 5 -s 2 -i input3.txt -o out.txt;
echo -e "\n\nB103\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 10 -s 2 -i input3.txt -o out.txt;
echo -e "\n\nB503\n" >> timelog;
/usr/bin/time -o timelog -a -p java Search Beam -k 50 -s 2 -i input3.txt -o out.txt;